version: '3.8'

services:
  backend:
    image: etown/owl:latest
    env_file:
      - .env
    environment:
      - OMP_NUM_THREADS=1
    shm_size: 3g
    ports:
      - '${OWL_WEB_API_PORT:-8000}:${OWL_WEB_API_PORT:-8000}'
    volumes:
      - .:/app

  web:
    image: etown/owl-web:latest
    env_file:
      - .env
    ports:
      - '${OWL_WEB_PORT:-3000}:${OWL_WEB_PORT:-3000}'
    depends_on:
      - backend
