#
# sample_config.yaml
#
# It is recommended you copy this up one level to the root of the source tree, from where the server
# will be run, and rename to config.yaml. Change settings as needed and specify
# --config=config.yaml when running the server.
#

# Configure this with your name and a create a secure token (which must also be entered into the 
# e.g. iOS client app)
user:
  name: "Bob"
  client_token: your_own_secret_token

# Choose an LLM. To use OpenAI models, 'api_key' must be valid and 'api_base_url' must remain blank.
llm:
  # Local mistral
    model: ollama/mistral:instruct
    api_base_url: http://localhost:11434
    api_key: 
    
  # OpenAI
  #
  # model: gpt-4-1106-preview
  # api_base_url: 
  # api_key: your_llm_api_key_if_needed


# Which provider to use for final transcription of captures.
async_transcription:
  provider: "whisper"
  #provider: "deepgram"

# Which provider to use for streaming transcription.
streaming_transcription:
  provider: "whisper"
  # provider: "deepgram"

# Deepgram configuration if using Deepgram for transcription.
deepgram:
  api_key: ""
  model: "nova-2"
  language: "en-US"

# Whisper model configuration if using Whisper for transcription.
async_whisper:
  host: "127.0.0.1"
  port: 8010
  hf_token: your_hugging_face_token
  device: cpu
  compute_type: int8
  batch_size: 16
  model: tiny
  verification_threshold: 0.1
  verification_model_source: speechbrain/spkrec-ecapa-voxceleb
  verification_model_savedir: pretrained_models/spkrec-ecapa-voxceleb

streaming_whisper:
  host: "127.0.0.1"
  port: 8009
  model: "small"
  language: "en"
  silero_sensitivity: 0.4
  webrtc_sensitivity: 2
  post_speech_silence_duration: 0.5

captures:
  capture_dir: captures

vad:
  vad_model_savedir: pretrained_models/vad

database:
  url: "sqlite:///./db.sqlite3"

conversation_endpointing:
  timeout_seconds: 300
  min_utterances: 2

notification:
  apn_team_id: ""

# Enable for LTE-M boards
udp:
  enabled: false
  host: '0.0.0.0'
  port: 8001

speaker_identification:
  provider: speech_brain
  voice_sample_directory: voice_samples

speech_brain:
  threshold: 0.2
  
# To enable web search
# bing:
#   subscription_key: your_bing_subscription_service_key